### PR TITLE
React Hello App: Frontend setup

### PR DESCRIPTION
**Pull request by patriciachrysy**
Create a new React app called 'hello-react-front-end'
Initialize your project with Git.
Create the App component with react-router.
Create the Greeting component that will display a greeting. Set it up as a route in your App component.
Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
Display the random greeting in your Greeting component.

### CODE REVIEW

**Comment by Reem-lab** [comment]
Hello @patriciachrysy  Could you check the linters here?

**Comment by patriciachrysy** [comment]
> Hello @patriciachrysy Could you check the linters here?
 The job is not running
Do you have any idea why please?

**Comment by Reem-lab** [comment]
Hello @patriciachrysy please reach out via Slack?

**Comment by patriciachrysy** [comment]
> Hello @patriciachrysy please reach out via Slack?
@Reem-lab I left a message for you on slack

**Comment by patriciachrysy** [comment]
> Hello @patriciachrysy please reach out via Slack?

I successfully solved the linters but removed the stylelint config since i do not have any css

**Pull request merged**
